# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 04:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_auto_20170913_0426'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllSensors',
            new_name='Sensors',
        ),
    ]
