# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_auto_20170913_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='as1',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensors',
            name='as2',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensors',
            name='ps1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sensors',
            name='ps2',
            field=models.FloatField(default=0),
        ),
    ]
