# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_auto_20171006_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='wl',
            field=models.FloatField(default=0),
        ),
    ]
