# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0008_sensors_wl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensors',
            old_name='humidity',
            new_name='dw',
        ),
        migrations.RenameField(
            model_name='sensors',
            old_name='ps1',
            new_name='ps',
        ),
        migrations.RenameField(
            model_name='sensors',
            old_name='ps2',
            new_name='spw',
        ),
        migrations.RenameField(
            model_name='sensors',
            old_name='temperature',
            new_name='ss',
        ),
        migrations.RenameField(
            model_name='sensors',
            old_name='wl',
            new_name='tpw',
        ),
        migrations.RemoveField(
            model_name='sensors',
            name='as1',
        ),
        migrations.RemoveField(
            model_name='sensors',
            name='as2',
        ),
    ]
